# Monara Linux - Name Service Switch
passwd:    files
shadow:    files
group:     files
hosts:     files dns
networks:  files
services:  files
protocols: files
rpc:       files
ethers:    files
netgroup:  files
