#
# /etc/pacman.conf - Monara Linux
#

[options]
RootDir     = /
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
HoldPkg     = pacman glibc
Architecture = auto
Color
ParallelDownloads = 10
CheckSpace

# Monara core repository (local)
[monara]
SigLevel = Optional TrustAll
Server = file:///var/lib/pacman/local
